### ISSUE TITLE
Add slot 2 expansion for ngpds for 2 games to be playable

### ISSUE THREAD

**Issue by Rnzei** [FluBBaOfWard/NGPDS#10]
I think if you add this its will be amazing all tye ngc game can be playable on the ds 
And plus the 2 game need the expansion pak is the besygame the neo geo pocket color have pls add it

**Comment by FluBBaOfWard** [comment]
Can you stop making new issues for the same thing over and over? Please!
https://github.com/FluBBaOfWard/NGPDS/issues/5
https://github.com/FluBBaOfWard/NGPDS/issues/8

**Comment by Rnzei** [comment]
Okie ill stop

**Comment by Rnzei** [comment]
Hello FluBBaOfWard i saw the ngpc page is updated nice but hoe do you
compile it the so i can make the ngpc 5.6 version so i could play snk vs
capcom neogeo pocket
Btw ty for you work

**Comment by Rnzei** [comment]
I cant download new update no pc pls compile plsssss :(

**Comment by Rnzei** [comment]
Broooooooooooooooooooooooo how to download it?
