### ISSUE TITLE
Compile fails if following changes are not applied

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/NGPDS#3]
diff --git a/source/FileHandling.c b/source/FileHandling.c
index 76effaa..953a5f3 100644
--- a/source/FileHandling.c
+++ b/source/FileHandling.c
@@ -11,7 +11,7 @@
 #include "Shared/EmuMenu.h"
 #include "Shared/EmuSettings.h"
 #include "Shared/FileHelper.h"
-#include "Shared/unzip/unzipnds.h"
+#include "Shared/Unzip/unzipnds.h"
 #include "Main.h"
 #include "Gui.h"
 #include "Cart.h"
diff --git a/source/bios.c b/source/bios.c
index f43e312..55f9442 100644
--- a/source/bios.c
+++ b/source/bios.c
@@ -17,7 +17,7 @@
 #include "bios.h"
 #include "K2GE/K2GE.h"
 #include "Shared/EmuMenu.h"
-#include "Filehandling.h"
+#include "FileHandling.h"
 #include "TLCS900H/TLCS900H.h"
 
 //=============================================================================

**Comment by FluBBaOfWard** [comment]
Working now?

**Comment by Ntemis** [comment]
Working! gtg
