### ISSUE TITLE
Puzzle Link/Puzzle Link 2 (USA, EU) sometimes softlocks when a level ends

### ISSUE THREAD

**Issue by kokoropaint** [FluBBaOfWard/NGPDS#4]
Hi, not sure if this is the best place to send error reports but I've been running into this issue regardless of what settings I use. I'm on a DSi using NGPDS through TwilightMenu.

It seems like this has a chance of happening regardless of what game mode you're playing.

For Puzzle Link 2, the game softlocked but kept music playing when I finished an Endless round (after submitting my score) and when clicking "Card Mode" on the main menu.

**Comment by FluBBaOfWard** [comment]
This is probably a bug in the CPU core, Sonic can end up waiting for the boss on the first stage.
I haven't looked in to it really, would help if there was a cpu tester program.

**Comment by FluBBaOfWard** [comment]
Is this still an issue in the latest release?
