### ISSUE TITLE
Add 4mb games support

### ISSUE THREAD

**Issue by Rnzei** [FluBBaOfWard/NGPDS#5]
There's only two 4mb games I know snk vs capcom match of the melemiun and metal slug 2nd mission pls add

**Comment by FluBBaOfWard** [comment]
These are the first few lines of code in Main.c
`	maxRomSize = 0x400000;
	romSpacePtr = malloc(maxRomSize);
	if (romSpacePtr == NULL) {
		maxRomSize = 0x200000;
		romSpacePtr = malloc(maxRomSize);
	}
`
This means that if the code is able to allocate 4MB it will do that, if it's not able it will only allocate 2MB.
The DS and DS-Lite only have 4MB of RAM where the emulator has to live as well, on the DSi which has 16MB of RAM it will have 4MB for the games.

**Comment by Rnzei** [comment]
Bro I don't really know how many ram nds does  I just bought an nds weeks
ago I really wanted to play snk vs capcom match of melemiun that's it

**Comment by Rnzei** [comment]
Hello flubba
Imbhere agian pls add slot 2 expansion ram for the ngpds to load 2 games pls
